const imagesPool = [
  'images/Drivers/albon_front.png',
  'images/Drivers/alonso_front.png',
  'images/Drivers/bottas_front.png',
  'images/Drivers/de_vries_front.png',
  'images/Drivers/gasly_front.png',
  'images/Drivers/hamilton_front.png',
  'images/Drivers/hulkenberg_front.png',
  'images/Drivers/latifi_front.png',
  'images/Drivers/leclerc_front.png',
  'images/Drivers/kevin_magnussen_front.png',
  'images/Drivers/norris_front.png',
  'images/Drivers/ocon_front.png',
  'images/Drivers/perez_front.png',
  'images/Drivers/ricciardo_front.png',
  'images/Drivers/russell_front.png',
  'images/Drivers/sainz_front.png',
  'images/Drivers/mick_schumacher_front.png',
  'images/Drivers/stroll_front.png',
  'images/Drivers/tsunoda_front.png',
  'images/Drivers/max_verstappen_front.png',
  'images/Drivers/vettel_front.png',
  'images/Drivers/zhou_front.png',
];

export default imagesPool;
