const imagesPool2 = [
  'images/circuits/albert_park.png',
  'images/circuits/americas.png',
  'images/circuits/bahrain.png',
  'images/circuits/baku.png',
  'images/circuits/catalunya.png',
  'images/circuits/hungaroring.png',
  'images/circuits/imola.png',
  'images/circuits/interlagos.png',
  'images/circuits/jeddah.png',
  'images/circuits/marinabay.png',
  'images/circuits/miami.png',
  'images/circuits/monaco.png',
  'images/circuits/monza.png',
  'images/circuits/red_bull_ring.png',
  'images/circuits/ricard.png',
  'images/circuits/rodriguez.png',
  'images/circuits/silverstone.png',
  'images/circuits/spa.png',
  'images/circuits/suzuka.png',
  'images/circuits/villeneuve.png',
  'images/circuits/yas_marina.png',
  'images/circuits/zandvoort.png',
];

export default imagesPool2;
